# Generated by Django 3.1.12 on 2025-10-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.TextField()),
                ('propietario', models.TextField()),
                ('descripcion', models.TextField()),
                ('asignado', models.TextField()),
                ('fecha_inicio_trabajo', models.DateField()),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_accesorios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(upload_to='motos/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
