name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      # Aunque el error fue por 3.7, mantenemos la estrategia.
      max-parallel: 4 
      matrix:
        # Versiones de Python modernas y soportadas
        python-version: [3.8, 3.9, 3.10, 3.11] 

    steps:
    - uses: actions/checkout@v4
    
    # Usamos v5, la versión más reciente de la acción setup-python
    - name: Set up Python ${{ matrix.python-version }} 
      uses: actions/setup-python@v5 
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        # Aseguramos la última versión de pip
        python -m pip install --upgrade pip
        # Instala las dependencias de tu archivo requirements.txt
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        # Asume que tienes un archivo manage.py en la raíz del repositorio
        python manage.py test
