name: Django CI & Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # --- JOB 1: TEST MATRIX ---
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies (incluye Pillow)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt Pillow

      - name: Django checks & tests
        env:
          DJANGO_SETTINGS_MODULE: myproject.settings
        run: |
          python manage.py check
          python manage.py test

  # --- JOB 2: DEPLOY A HEROKU (solo cuando test pasa y es push a main) ---
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies for build (incluye Pillow y gunicorn)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt Pillow gunicorn

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: false

      - name: Run migrations on Heroku
        run: |
          curl -n -X POST https://api.heroku.com/apps/${{ secrets.HEROKU_APP_NAME }}/dynos \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3" \
          -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
          -d \'\'\'{"command":"python manage.py migrate --noinput","type":"run"}\'\'\'

      - name: Collect static on Heroku
        run: |
          curl -n -X POST https://api.heroku.com/apps/${{ secrets.HEROKU_APP_NAME }}/dynos \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3" \
          -H "Authorization: Bearer ${{ secrets.HEROKU_API_KEY }}" \
          -d \'\'\'{"command":"python manage.py collectstatic --noinput","type":"run"}\'\'\'
