name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      # (Opcional) Solo si Pillow llegara a compilar desde fuente y pidiera libs del sistema:
      # - name: System deps for Pillow
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libjpeg-dev zlib1g-dev

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt Pillow

      - name: Run Tests
        run: |
          python manage.py test
